import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Play, Sparkles, Code, Loader2 } from "lucide-react";

export function DemoSection() {
  const [prompt, setPrompt] = useState("");
  const [response, setResponse] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleDemo = async () => {
    if (!prompt.trim()) return;
    
    setIsLoading(true);
    setResponse("");
    
    try {
      const response = await fetch('/api/gemini-chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: `Generate a React component for: ${prompt}. Please provide clean, modern code with TypeScript, using Tailwind CSS for styling. Include proper props and export the component.`
        })
      });

      const data = await response.json();
      
      if (data.error) {
        throw new Error(data.error);
      }
      
      setResponse(data.response || 'No response generated');
    } catch (error) {
      console.error('Error calling Gemini API:', error);
      // Fallback to demo response
      const demoResponse = `// Generated React Component (Demo)
import React from 'react';
import { Button } from '@/components/ui/button';

export function ${prompt.replace(/\s+/g, '')}Component() {
  return (
    <div className="p-6 max-w-md mx-auto bg-white rounded-xl shadow-lg">
      <h2 className="text-xl font-bold mb-4">${prompt}</h2>
      <p className="text-gray-600 mb-4">
        This component was generated by LadeStack AI based on your prompt.
      </p>
      <Button>Get Started</Button>
    </div>
  );
}

// Note: This is a demo response. Connect with full AI for advanced features.`;
      
      setResponse(demoResponse);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section id="demo" className="py-24 bg-muted/30">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center space-x-2 bg-card/50 backdrop-blur-sm border border-border rounded-full px-4 py-2 mb-6">
            <Sparkles className="w-4 h-4 text-primary animate-pulse" />
            <span className="text-sm font-medium">Interactive AI Demo</span>
          </div>
          
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Try Our <span className="gradient-text">AI Tools</span>
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto text-balance">
            Experience the power of AI-assisted development. Describe what you want to build, 
            and watch our AI generate code in real-time.
          </p>
        </div>

        {/* Demo interface */}
        <div className="card-elegant p-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Input side */}
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium mb-3 text-foreground">
                  Describe your component:
                </label>
                <Input
                  placeholder="e.g., User Profile Card, Login Form, Dashboard Widget"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="mb-4"
                />
                <Button 
                  onClick={handleDemo}
                  disabled={!prompt.trim() || isLoading}
                  className="btn-gradient w-full group"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 w-4 h-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Play className="mr-2 w-4 h-4 group-hover:scale-110 transition-transform" />
                      Generate Component
                    </>
                  )}
                </Button>
              </div>

              {/* Features */}
              <div className="space-y-3 pt-6 border-t border-border">
                <h4 className="font-medium text-foreground mb-3">What you can build:</h4>
                <div className="grid grid-cols-1 gap-2 text-sm text-muted-foreground">
                  <div className="flex items-center space-x-2">
                    <Code className="w-4 h-4 text-primary" />
                    <span>React Components</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Code className="w-4 h-4 text-primary" />
                    <span>API Endpoints</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Code className="w-4 h-4 text-primary" />
                    <span>Database Schemas</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Code className="w-4 h-4 text-primary" />
                    <span>CSS Styles</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Output side */}
            <div className="space-y-4">
              <label className="block text-sm font-medium text-foreground">
                Generated Code:
              </label>
              <div className="relative">
                <Textarea
                  value={response || "// Your generated code will appear here..."}
                  readOnly
                  className="min-h-[300px] font-mono text-sm bg-muted/50 border-border"
                  style={{ resize: 'none' }}
                />
                {isLoading && (
                  <div className="absolute inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center rounded-md">
                    <div className="flex items-center space-x-3">
                      <Loader2 className="w-6 h-6 animate-spin text-primary" />
                      <span className="text-sm text-muted-foreground">AI is thinking...</span>
                    </div>
                  </div>
                )}
              </div>
              
              {response && (
                <Button variant="outline" size="sm" className="w-full">
                  <Code className="mr-2 w-4 h-4" />
                  Copy Code
                </Button>
              )}
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <p className="text-muted-foreground mb-4">
            This is just a preview. Our full platform offers much more!
          </p>
          <Button size="lg" className="btn-gradient">
            Explore All Tools
          </Button>
        </div>
      </div>
    </section>
  );
}